### PR TITLE
Feature/homepage

### PR DESCRIPTION
**Pull request by cliftondavies**
# Project: Building with Responsive Design
## Milestones
- [x] Setup files
- [x] A fullyresponsiveclone of The Next Web.
- [x] HTML and CSS Validator
- [x] Local Stylelint
- [x] GitHub Stickler
- [x] README

Please see the feature/homepage branch for completed project and full commit history, as I encountered some issues when trying to create a pull request against master.

I started within a local repo, and created the feature/homepage branch. I also linked the repo to the remote one created on github, and set up a tracking branch as well.

Everything worked fine until now when I tried to create a pull request to compare my feature/homepage branch against base master. Github came up with an error saying "refusing to merge unrelated histories."

The only way I could solve it was to run `git pull origin master --allow-unrelated-histories` locally, resolve resulting merge errors, commit and push to the remote master branch. However, this came with the unintended effect of pushing all progress in the local feature/homepage branch to the remote master branch, and putting the remote master branch ahead by two commits.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE) 

### Hello @cliftondavies :wave:  :balloon:  
### First of all claps to your attention to detail :clap: :microscope: this project exceeds it :star2:  thank you for explaining the situation I can see all the commits in the master. :memo: There are still a couple of changes to make before we can give you the approval:

**Latest fundings (middle screen)**

- [ ] The menu should have a particular order: See more | Get updates by email | Add info

image

**Latest fundings (small screen)**

- [ ] The menu also has a particular order:
 
image

**General**

- [ ] Linters config: your Linters aren't working, perhaps you need to activate the repo in [stickler](https://stickler-ci.com/)

**Section specific**

- [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload)

### That is it! :raised_hands:  its been a blast :guitar:  reviewing this project please :pray: make the changes and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

STATUS OF THE PROJECT: REQUESTED CHANGES :traffic_light:

**Comment by cliftondavies** [comment]
Hi @euqueme :wave: 

Thanks for the feedback :pray:

**Changes Made As Requested - See Demo Link in Master README**
- [x] Activated the repo in Stickler
- [x] Set the order of links in the Funding section to change as the screen gets to middle and small

I validated the HTML before the initial pull request, and only had one warning, which I have resolved now.

That was a really good spot on the links :raised_hands: For all my attention to detail I still missed it :smile:. Stickler was an oversight, I was too focused on resolving the unrelated histories issue I encountered.

Thanks again!

**Review by rOluochKe — APPROVED** [review]
Hello @cliftondavies 
### Congratulations, your project has been approved :clap: :boom:
### You can merge and submit a project completion form from your dashboard
### I wish you all the best in your next project
- Happy coding!

**Comment by cliftondavies** [comment]
Thanks @rOluochKe 🙏

**Pull request merged**
